#include <SFML/Graphics.hpp>
#include <SFML/Window.hpp>
#include <SFML/OpenGL.hpp>
// #include "game.cpp"
#include "obstacles.h"
#include<iostream>
#include<string>
std::vector<Obstacles> allObstacle;

class getRandomDove{
public:
    Obstacles dove1;
    Obstacles dove2;
    Obstacles dove3;
    Obstacles dove4;
    Obstacles dove5;
    Obstacles dove6;
    Obstacles dove7;
    Obstacles dove8;
    Obstacles dove9;
    Obstacles dove10;
    Obstacles dove11;
    Obstacles dove12;
    Obstacles dove13;
    Obstacles dove14;
    Obstacles dove15;
    Obstacles dove16;
    Obstacles dove17;
    Obstacles dove18;
    Obstacles dove19;
    Obstacles dove20;
    Obstacles dove21;
    Obstacles dove22;
    Obstacles dove23;
    Obstacles dove24;
    Obstacles dove25;
    Obstacles dove26;
    Obstacles dove27;
    Obstacles dove28;
    Obstacles dove29;
    Obstacles dove30;
    Obstacles dove31;
    Obstacles dove32;
    Obstacles dove33;
    Obstacles dove34;
    Obstacles dove35;
    Obstacles dove36;
    Obstacles dove37;
    Obstacles dove38;
    Obstacles dove39;
    Obstacles dove40;
    Obstacles trash1;
    Obstacles trash2;
    Obstacles trash3;
    Obstacles trash4;
    Obstacles trash5;
    Obstacles trash6;
    Obstacles trash7;
    Obstacles trash8;
    Obstacles trash9;
    Obstacles trash10;
    Obstacles trash11;
    Obstacles trash12;
    Obstacles trash13;
    Obstacles trash14;
    Obstacles trash15;
    Obstacles trash16;
    Obstacles trash17;
    Obstacles trash18;
    Obstacles trash19;
    Obstacles trash20;
    Obstacles trash21;
    Obstacles trash22;
    Obstacles trash23;
    Obstacles trash24;
    Obstacles trash25;
    Obstacles trash26;
    Obstacles trash27;
    Obstacles trash28;
    Obstacles trash29;
    Obstacles trash30;
    Obstacles trash31;
    Obstacles trash32;
    Obstacles trash33;
    Obstacles trash34;
    Obstacles trash35;
    Obstacles trash36;
    Obstacles trash37;
    Obstacles trash38;
    Obstacles trash39;
    Obstacles trash40;
    getRandomDove();
};
getRandomDove::getRandomDove()
{
    dove1.setDove();
    allObstacle.push_back(dove1);
    dove2.setDove();
    allObstacle.push_back(dove2);
    dove3.setDove();
    allObstacle.push_back(dove3);
    dove4.setDove();
    allObstacle.push_back(dove4);
    dove5.setDove();
    allObstacle.push_back(dove5);
    dove6.setDove();
    allObstacle.push_back(dove6);
    dove7.setDove();
    allObstacle.push_back(dove7);
    dove8.setDove();
    allObstacle.push_back(dove8);
    dove9.setDove();
    allObstacle.push_back(dove9);
    dove10.setDove();
    allObstacle.push_back(dove10);
    dove11.setDove();
    allObstacle.push_back(dove11);
    dove12.setDove();
    allObstacle.push_back(dove12);
    dove13.setDove();
    allObstacle.push_back(dove13);
    dove14.setDove();
    allObstacle.push_back(dove14);
    dove15.setDove();
    allObstacle.push_back(dove15);
    dove16.setDove();
    allObstacle.push_back(dove16);
    dove17.setDove();
    allObstacle.push_back(dove17);
    dove18.setDove();
    allObstacle.push_back(dove18);
    dove19.setDove();
    allObstacle.push_back(dove19);
    dove20.setDove();
    allObstacle.push_back(dove20);
    dove21.setDove();
    allObstacle.push_back(dove21);
    dove22.setDove();
    allObstacle.push_back(dove22);
    dove23.setDove();
    allObstacle.push_back(dove23);
    dove24.setDove();
    allObstacle.push_back(dove24);
    dove25.setDove();
    allObstacle.push_back(dove25);
    dove26.setDove();
    allObstacle.push_back(dove26);
    dove27.setDove();
    allObstacle.push_back(dove27);
    dove28.setDove();
    allObstacle.push_back(dove28);
    dove29.setDove();
    allObstacle.push_back(dove29);
    dove30.setDove();
    allObstacle.push_back(dove30);
    dove31.setDove();
    allObstacle.push_back(dove31);
    dove32.setDove();
    allObstacle.push_back(dove32);
    dove33.setDove();
    allObstacle.push_back(dove33);
    dove34.setDove();
    allObstacle.push_back(dove34);
    dove35.setDove();
    allObstacle.push_back(dove35);
    dove36.setDove();
    allObstacle.push_back(dove36);
    dove37.setDove();
    allObstacle.push_back(dove37);
    dove38.setDove();
    allObstacle.push_back(dove38);
    dove39.setDove();
    allObstacle.push_back(dove39);
    dove40.setDove();
    allObstacle.push_back(dove40);
    trash1.setTrash();
    allObstacle.push_back(trash1);
    trash2.setTrash();
    allObstacle.push_back(trash2);
    trash3.setTrash();
    allObstacle.push_back(trash3);
    trash4.setTrash();
    allObstacle.push_back(trash4);
    trash5.setTrash();
    allObstacle.push_back(trash5);
    trash6.setTrash();
    allObstacle.push_back(trash6);
    trash7.setTrash();
    allObstacle.push_back(trash7);
    trash8.setTrash();
    allObstacle.push_back(trash8);
    trash9.setTrash();
    allObstacle.push_back(trash9);
    trash10.setTrash();
    allObstacle.push_back(trash10);
    trash11.setTrash();
    allObstacle.push_back(trash11);
    trash12.setTrash();
    allObstacle.push_back(trash12);
    trash13.setTrash();
    allObstacle.push_back(trash13);
    trash14.setTrash();
    allObstacle.push_back(trash14);
    trash15.setTrash();
    allObstacle.push_back(trash15);
    trash16.setTrash();
    allObstacle.push_back(trash16);
    trash17.setTrash();
    allObstacle.push_back(trash17);
    trash18.setTrash();
    allObstacle.push_back(trash18);
    trash19.setTrash();
    allObstacle.push_back(trash19);
    trash20.setTrash();
    allObstacle.push_back(trash20);
    trash21.setTrash();
    allObstacle.push_back(trash21);
    trash22.setTrash();
    allObstacle.push_back(trash22);
    trash23.setTrash();
    allObstacle.push_back(trash23);
    trash24.setTrash();
    allObstacle.push_back(trash24);
    trash25.setTrash();
    allObstacle.push_back(trash25);
    trash26.setTrash();
    allObstacle.push_back(trash26);
    trash27.setTrash();
    allObstacle.push_back(trash27);
    trash28.setTrash();
    allObstacle.push_back(trash28);
    trash29.setTrash();
    allObstacle.push_back(trash29);
    trash30.setTrash();
    allObstacle.push_back(trash30);
    trash31.setTrash();
    allObstacle.push_back(trash31);
    trash32.setTrash();
    allObstacle.push_back(trash32);
    trash33.setTrash();
    allObstacle.push_back(trash33);
    trash34.setTrash();
    allObstacle.push_back(trash34);
    trash35.setTrash();
    allObstacle.push_back(trash35);
    trash36.setTrash();
    allObstacle.push_back(trash36);
    trash37.setTrash();
    allObstacle.push_back(trash37);
    trash38.setTrash();
    allObstacle.push_back(trash38);
    trash39.setTrash();
    allObstacle.push_back(trash39);
    trash40.setTrash();
    allObstacle.push_back(trash40);
}

